version: "3"

services:
    stockholm-service-test1:
        restart: always
        build:
            context: ./
            dockerfile: ./stockholm-service-test1/Dockerfile
        image: stockholm-service-test1
        ports:
        - 8082:6666
        volumes:
          - ./data1/:/var/lib/docker/volumes/logs/data1
    stockholm-service-test2:
        restart: always
        build:
            context: ./
            dockerfile: ./stockholm-service-test2/Dockerfile
        image: stockholm-service-test2
        ports:
        - 8083:5555
        volumes:
          - ./data2/:/var/lib/docker/volumes/logs/data2

volumes:
  data1:
    external: true
  data2:
    external: true