version: '3'
services:
  stockholm-service-dev:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: stockholm-service-dev
    ports:
    - 3102:8888
    volumes:
    - ./data/:/var/lib/docker/volumes/data
    deploy:
      resources:
        limits:
          cpus: 100m
          memory: 512Mi
        reservations:
          cpus: 100m
          memory: 512Mi
volumes:
  data:
    external: true