version: '3'
services:
  stockholm-service-dev:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: stockholm-service-dev
    ports:
    - 3102:8888
    volumes:
    - ./data/:/var/lib/docker/volumes/data
    - ./localtime/:/etc/localtime:ro
    - ./timezone/:/etc/timezone:ro

volumes:
  localtime:
    external: true
  timezone:
    external: true
  data:
    external: true