version: '3'
services:
  stockholm-service-dev:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: stockholm-service-dev
    ports:
    - 3102:8888
    volumes:
    - ./data/:/var/lib/docker/volumes/data
	- "/etc/localtime:/etc/localtime:ro"
	- "/etc/timezone:/etc/timezone:ro"
volumes:
  data:
    external: true