server.port=5555
application.config.profileName=test2

# security
security.oauth2.client.grant-type=password
security.oauth2.client.client_id=3MVG9ZUGg10Hh225k7LKccisq1JqzOsfUI9bJPvYu_y4P5uwrMek35VAcVDybfRsA4pos7BjGvGFH9XNfApI9
security.oauth2.client.client_secret=C60FA6E1FB5804806D12BDDADFEC9890077A6C90E207C81FAE3F7210C5A1AAA6
security.oauth2.client.username=nguyen.son@japantaxi.co.jp.comtest
security.oauth2.client.password=9akNMo7rGyJi5wYtAjVtTgSCswKROMLeGrJ6p
security.oauth2.client.access_token_uri=https://test.salesforce.com/services/oauth2/token

# stockholm ds
stockholm.datasource.driverClassName=org.postgresql.Driver
stockholm.datasource.jdbcUrl=jdbc:postgresql://172.16.210.39:5432/stockholmserivce?currentSchema=lan
stockholm.datasource.username=postgres
stockholm.datasource.password=1qaz2wsx

# brooklyn ds
brooklyn.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
brooklyn.datasource.jdbcUrl=jdbc:sqlserver://172.16.210.39;databaseName=taxicall2
brooklyn.datasource.username=SA
brooklyn.datasource.password=ADmin@1234

# sentry
sentry.dsn=https://d025f7fd08ee4d8e9b3aa6122b128734@sentry.io/5174022

# salesforce
sf.version=v1

batch.code=SBAT-001