server.port=8888
application.config.profileName=dev

# Salesforce
#security.oauth2.client.grant-type=password
#security.oauth2.client.client_id=3MVG9ZUGg10Hh225k7LKccisq1JqzOsfUI9bJPvYu_y4P5uwrMek35VAcVDybfRsA4pos7BjGvGFH9XNfApI9
#security.oauth2.client.client_secret=C60FA6E1FB5804806D12BDDADFEC9890077A6C90E207C81FAE3F7210C5A1AAA6
#security.oauth2.client.username=nguyen.son@japantaxi.co.jp.comtest
#security.oauth2.client.password=9akNMo7rGyJiuOlW40Yjuuu6DMOHMZnxF6q4
#security.oauth2.client.access_token_uri=https://test.salesforce.com/services/oauth2/token

#security.oauth2.client.grant-type=password
#security.oauth2.client.client_id=3MVG9z6NAroNkeMm8GFWHUC8IbVc5MyC6g0GKQpPHcccQsNb3IA1il9S8EOh1nj86Xr9PzxiXTWLPtafjmj8t
#security.oauth2.client.client_secret=2632B93CE11B55E97187476EB56FD0956AB7CFF48E3B036D4989BF7F9B1B7F7D
#security.oauth2.client.username=nguyen.son@japantaxi.co.jp.test1
#security.oauth2.client.password=9akNMo7rGyJi1pOkyXlhFb5egeKoeTOkT3gmm
#security.oauth2.client.access_token_uri=https://test.salesforce.com/services/oauth2/token

#security.oauth2.client.grant-type=password
#security.oauth2.client.client_id=3MVG9Po2PmyYruumLfVc4MhJKLNz0RwWOV3WMKVOD3qdYp0v0Xxv0ay1al.a6zlZYrAz5h3fqYc9eFmTfebr3
#security.oauth2.client.client_secret=951953468268E98AF397DF7D8A8D03339E09590F25CC82B5CAAB5ECD7FDE9A95
#security.oauth2.client.username=devcowell@mo-t.com.stg
#security.oauth2.client.password=9akNMo7rGyJiCKGbhXBXws85mPFLT8D30kpnK
#security.oauth2.client.access_token_uri=https://test.salesforce.com/services/oauth2/token

security.oauth2.client.grant-type=password
security.oauth2.client.client_id=3MVG9iLRabl2Tf4jwJlO1e7cGqtioapNRCsAljK06I9hao0PsRCuBDgN.T6LXm8bVS3H.mM.l39ogcPKNGX91
security.oauth2.client.client_secret=026D0CDEE9E20AF365C82EDEC5FEC223609AFEBE47EF94B0571B27570C99FBE4
security.oauth2.client.username=devcw@mo-t.com.cowell
security.oauth2.client.password=Mot@2020
security.oauth2.client.access_token_uri=https://test.salesforce.com/services/oauth2/token

sf.version=v1


# Stockholm DB	# Stockholm DB
stockholm.datasource.driverClassName=org.postgresql.Driver
stockholm.datasource.jdbcUrl=jdbc:postgresql://172.16.210.39:3105/stockholmserivce?currentSchema=jtx
stockholm.datasource.username=postgres
stockholm.datasource.password=1qaz2wsx


# Sentry
sentry.dsn=https://d025f7fd08ee4d8e9b3aa6122b128734@sentry.io/5174022


# Batchcode
batch.code=SBAT-001

domain.allowed=localhost